name: $(Date:yyyyMMdd)$(Rev:.r) # build numbering format

trigger: none

variables:
  - workingDirectory: "."

strategy:
  matrix:
    macOS:
      vmImage: "macOS-latest"
    windows:
      vmImage: "windows-latest"
    ubuntu:
      vmImage: "ubuntu-latest"
pool:
  vmImage: $(ubuntu)

steps:
  - task: NodeTool@0
    inputs:
      checkLatest: true
      versionSpec: 10.x
    displayName: "Use Node 10.x"
    workingDirectory: "."

  - bash: |
      npm ci
    displayName: "Install dependencies"

  - bash: |
      npm run lint
    displayName: "Linting markdown files"
    workingDirectory: "."
